[package]
name = "chik-datalayer"
version = "0.34.0"
edition = "2021"
license = "Apache-2.0"
description = "DataLayer modules for Chik blockchain"
authors = ["Chik Network, Inc. <hello@chiknetwork.com>"]
homepage = "https://github.com/Chik-Network/chik_rs"
repository = "https://github.com/Chik-Network/chik_rs"

[lints]
workspace = true

[features]
py-bindings = ["dep:pyo3", "dep:chik_py_streamable_macro", "chik-protocol/py-bindings"]
arbitrary = ["dep:arbitrary", "chik-protocol/arbitrary"]

[lib]
crate-type = ["rlib"]

[dependencies]
num-traits = { workspace = true }
pyo3 = { workspace = true, optional = true }
thiserror = { workspace = true }
bitvec = { workspace = true }
indexmap = { workspace = true }
chik_py_streamable_macro = { workspace = true, optional = true }
chik_streamable_macro = { workspace = true }
chik-datalayer-macro = { workspace = true }
chik-traits = { workspace = true }
chik-sha2 = { workspace = true }
chik-protocol = { workspace = true }
rayon = { workspace = true }
zstd = { workspace = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
klvm-utils = { workspace = true }
expect-test = { workspace = true }
hex = { workspace = true }
open = { workspace = true }
percent-encoding = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
url = { workspace = true }
tempfile = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["chik-sha2"]
