[package]
name = "clvk-traits"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
description = "Traits for encoding and decoding CLVK objects."
authors = ["Brandon Haggstrom <b.haggstrom@chiknetwork.com>"]
homepage = "https://github.com/Chik-Network/chik_rs"
repository = "https://github.com/Chik-Network/chik_rs"

[package.metadata.docs.rs]
features = ["derive", "chik-bls"]

[lints]
workspace = true

[features]
derive = ["dep:clvk-derive"]
chik-bls = ["dep:chik-bls"]
chik-secp = ["dep:chik-secp"]
py-bindings = ["dep:pyo3"]

[dependencies]
pyo3 = { workspace = true, optional = true }
clvkr = { workspace = true }
clvk-derive = { workspace = true, optional = true }
chik-bls = { workspace = true, optional = true }
chik-secp = { workspace = true, optional = true }
num-bigint = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
hex-literal = { workspace = true }
rstest = { workspace = true }
